remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
title: [An analysis of Ashe's objective and damage impacts.]
description: [Using permutation tests, the data suggests Ashe support is not as impactful as Ashe bot.]
