remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
title: [An analysis of Ashe's damage and objective impacts.]
description: [Through permutation testing, I have found that the data suggests Ashe support is not as impactful as Ashe bot.]
